### PR TITLE
SOLVES: #147 GSSOC'22

### LINKED ISSUE #147: Matrix Calculator
### Calculator Functions

This calculator will perform simple arithmetic operations like addition, subtraction or multiplication on 2 matrices
.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by BIKRAM-SAHA**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #147 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

[](https://postimg.cc/KkHfyVWg)
[](https://postimg.cc/LhPLXnYW)
[](https://postimg.cc/B8t1G6fM)

### CODE REVIEW

**Comment by AnuragParashar2000** [comment]
@BIKRAM-SAHA Please provide ScreenShots of your calculator.

**Comment by BIKRAM-SAHA** [comment]
@AnuragParashar2000 I have updated the comment with screenshots

**Comment by BIKRAM-SAHA** [comment]
@mansi-garg-12 
Are you talking about these two? 
image
- first one: is the readme.md for my project (Added)
- second one: is the main readme.md at the root folder (Modified to add my project at the calculators list)
<br>
I guess it adheres to the guidelines at main readme.md file under steps to contribute:

```
Add all necessary information like functionalities, screenshots, working video(if required) in the readme.md file. (you will have to create it in your newely created folder)
Add your folder's link in the main readme.md file of the repo.
```

**Review by vasu-1 — APPROVED** [review]
LGTM @BIKRAM-SAHA

**Pull request merged**
