### PR TITLE
Loan Calculator

### PR DESCRIPTION
**Pull request by abhi1e9-1e10**
## Description 📜

The main objective of this project is to calculate and displays the results for monthly payment, total payment, and total interest according to loan amount interest rate, and years to repay.

Fixes # <3>

<hr>
 
## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GSSOC'22 contributor

<hr>

### CODE REVIEW

**Comment by abhi1e9-1e10** [comment]
Is all ok or I can change something else?

**Review by mansi-garg-12 — APPROVED** [review]
Good to go checked!!!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
- Remove the license
- Also remove license from your readme
- Make it responsive !!

image

- And, Result is not showing to me! can you please confirm ?

**Comment by vasu-1** [comment]
@mansi-garg-12

**Pull request closed without merging**
