### PR TITLE
Simple arithmetic

### LINKED ISSUE #1: Number system calculator
### Calculator Functions

conversion for decimal to binary,octal,hexadecimal and vice versa.
I am  contributor in  GSSOC-22
can you assign this issue to me?

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### LINKED ISSUE #2: [Create New Issue]: Matrix Adjoint and Inverse Calculator
### Calculator Functions

Take User Input Matrix and display the Adjoint and Inverse of that matrix.

I would like to work on this issue can you assign this to me.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### LINKED ISSUE #3: Loan Calculator
### Calculator Functions

The main objective of this project is to calculate and displays the results for monthly payment, total payment, and total interest according to loan amount interest rate, and years to repay.
Key concepts covered :-

1.) document.querySelector()
2.) setInterval()
3.) Math.pow()
4.) toFixed()
5.) parseFloat()
6.) DOM manipulation
7.) JavaScript CSS Manipulation
8.) eventListener()

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by TusharKesarwani**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #1 Added functionalities in simple arithmetic calculator
Fixes #2 Changed design of the calculator
Fixes #3 Made responsive
<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Calculator

<hr>

### CODE REVIEW

**Comment by TusharKesarwani** [comment]
Done with changes

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Remove Calculators/Simple_Arithmetic/_config.yml this file

**Comment by TusharKesarwani** [comment]
Done with changes.

**Review by vasu-1 — APPROVED** [review]
LGTM @TusharKesarwani

**Comment by TusharKesarwani** [comment]
Thank you @vasu-1 sir for merging this PR and also for the appreciation.

**Pull request merged**
