### PR TITLE
binomial coefficient calculator

### LINKED ISSUE #296: binomial coefficient calculator
### Calculator Functions

this calculator is used for calculating the value of binomial coefficient by taking the values of n and k from the user and returns the answer.if there is any discrepancy that too will be displayed.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by 14anirudh**
## Description 📜
This calculator is used for the calculation of binomial coefficient by taking the value of n and k from the user 
Fixes #296

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
demoimg

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Remove `.vscode/settings.json`

**Comment by 14anirudh** [comment]
@vasu-1 please add the level tag so that i can get the points

**Comment by 14anirudh** [comment]
Please merge my PR i have done all the Changes

**Review by vasu-1 — APPROVED** [review]
LGTM @14anirudh

**Pull request merged**
