### PR TITLE
Added Color Code Calculator files

### LINKED ISSUE #88: Color Code Converter
### Calculator Functions

Converts between different color code formats such as RGB, CMYK, Hex, & Hsl.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by XZANATOL**
## Description 📜

Added color code calculator files that converts between different color code formats such as RGB, CMYK, Hsl, & Hex.

Fixes #88 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

Capture

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove the .png file and add a screenshot in readme.md

**Comment by XZANATOL** [comment]
@mansi-garg-12 I think there is a miss-understanding. The image in the screenshot section in the readme.md is the same .png you're asking me to remove.

The screenshot already exists in the readme.md

**Comment by mansi-garg-12** [comment]
Remove this file Calculators/Color_Code_Converter/assets/media/Capture.PNG
There is no need of this file and directly paste the screenshot in README.md.

**Comment by XZANATOL** [comment]
@mansi-garg-12 Done..

**Review by mansi-garg-12 — APPROVED** [review]
Checked Good Work!!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image

Just mention here which type of input should be entered in input box!!

And make it responsive & use some css for button and other elements!

**Comment by XZANATOL** [comment]
@vasu-1 Done.

**Comment by XZANATOL** [comment]
@vasu-1 any updates about the review?

**Review by vasu-1 — APPROVED** [review]
LGTM @XZANATOL

**Pull request merged**
