### PR TITLE
Electricity Bill Calculator, Issue #213

### LINKED ISSUE #213: Electricity Calculator
### Calculator Functions

Calculating the electricity bill based on units is always a tedious task, considering the fluctuation of rates as per unit.
So, This calculator focuses on resolving this issue, as a simple web-based electricity bill calculator. Enter the units of electricity consumed, and the program will compute the amount due or the amount to be paid.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by AnIkeT126**
## Description 📜

This is a simple web-based electricity bill calculator. Calculating the electricity bill based on units is always a tedious task, considering the fluctuation of rates as per unit. Here you just need to enter the units of electricity consumed, and the program will compute the amount due or the amount to be paid.

Fixes #213 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@vasu-1 please review this and merge the PR adding the level label if it looks fine to you.

**Review by Chayan-11 — APPROVED** [review]
Good one @AnIkeT126

**Comment by AnIkeT126** [comment]
@Chayan-11 ans @vasu-1 is it good to go for merge or not?

**Comment by Chayan-11** [comment]
> @Chayan-11 and @vasu-1 is it good to go for merge or not?

yeah wait for @vasu-1 to review it !

**Comment by AnIkeT126** [comment]
Ok I will make it responsive

**Pull request closed without merging**
