### PR TITLE
Enhancement in Temperature Calculator

### LINKED ISSUE #292: Enhancement in Temperature Calculator
The Temperature Calculator contains the following scales: Celsius, Fahrenheit, and Kelvin. 

I'd like to add Rankine scale as an enhancement. I'm a GSSOC'22 contributor and I'd like to be assigned this issue.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Description 📜

- Updated Temperature Calculator to include Rankine Scale
- Updated corresponding README file

Fixes #292 

<hr>
 
## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSOC'22 contributor
- [X] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot_2022-05-15-19-42-03-919_com android chrome

https://user-images.githubusercontent.com/80174214/168477576-adf2902a-df2d-42eb-a670-fe1a7ffadf44.mp4

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
If you wish to enhance this, can you work on the design and improve the UI ?

**Review by Chayan-11 — COMMENTED** [review]
@vasu-1 Please check this

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please improve the UI and Ux and try to add some more features in it.

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Improve the responsiveness and ui ! make it a bit unique !

**Comment by abhilipsasahoo03** [comment]
Hi @mansi-garg-12 due to time constraints and bad health since past few weeks, I won't be able to make any further improvements. If possible kindly merge the PR just as it is.

**Comment by vasu-1** [comment]
> is

It's fine

**Review by vasu-1 — APPROVED** [review]
LGTM

**Pull request merged**
