### PR TITLE
Compound interest calculator

### LINKED ISSUE #162: Compound_ Interest Calculator
### Calculator Functions

It will find out the compound interest .I would like to work on it.
Please assign me!

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by RiyaJain12**
This is the calculator that calculates the compound interest.It will take the value of principle amount,time period,rate in percentage,number of times the interest compounded and provide the values of interest and the total amount

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #162 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (137)

<hr>

### CODE REVIEW

**Comment by RiyaJain12** [comment]
update

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Code is good to go but try to make it Responsive.

**Comment by RiyaJain12** [comment]
@mansi-garg-12 Done!

**Review by mansi-garg-12 — APPROVED** [review]
Approved!! Ready to merge

**Comment by RiyaJain12** [comment]
@vasu-1 I did some changes now is perfectly responsive ,please check it!

**Pull request closed without merging**
