### PR TITLE
Resonant Frequency Calculator

### PR DESCRIPTION
**Pull request by Arun9739**
## Description 📜

Issue Number :  #223 
I have created the the Resonant Frequency Calculator, which gives the answer by taking capacitance and inductance. Also the web is responsive.

Designed using :
HTML
CSS
JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Arun9739** [comment]
@mansi-garg-12 @vasu-1 please review my pr

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Nice Work !!
but Make is Responsive for phone and tablet.

**Comment by Arun9739** [comment]
@mansi-garg-12 ma'am I have made the web site responsive for all the devices. Please review it.

**Review by mansi-garg-12 — APPROVED** [review]
Nice work Good to go....

**Pull request merged**
