### PR TITLE
Added SIP Calculator

### LINKED ISSUE #277: SIP Calculator
### Calculator Functions

This Calculator will calculate the Maturity amount after Investing Period
Screenshot 2022-05-18 at 10 05 12 AM

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by dhruvdabhi101**
## Description 📜

Created SIP Calculator.
Fixes #277 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove binary files and this PR contain two README.md file.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Still it contain two readme.md file

**Comment by dhruvdabhi101** [comment]
> Still it contains two readme.MD file

I think because I have changed the repo's readme file as it was mentioned in the instructions.. and there is a calculator's repo which we have to include in each calculator.

guide me if I'm missing something

**Comment by dhruvdabhi101** [comment]
so should i delete repo's readme file ??

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Improve your design !

**Comment by vasu-1** [comment]
Also add screenshot in the issue body!

**Comment by vasu-1** [comment]
> Improve your design !

@dhruvdabhi101

**Pull request closed without merging**
