### PR TITLE
Electricity Calculator, resolving issue #213, update on PR #215

### LINKED ISSUE #213: Electricity Calculator
### Calculator Functions

Calculating the electricity bill based on units is always a tedious task, considering the fluctuation of rates as per unit.
So, This calculator focuses on resolving this issue, as a simple web-based electricity bill calculator. Enter the units of electricity consumed, and the program will compute the amount due or the amount to be paid.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by AnIkeT126**
## Description 📜

This is a simple web-based electricity bill calculator. Calculating the electricity bill based on units is always a tedious task, considering the fluctuation of rates as per unit. Here you just need to enter the units of electricity consumed, and the program will compute the amount due or the amount to be paid.

Fixes #213 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@Chayan-11 and @vasu-1 this is an updated PR  on #215 and issue #213 with the necessary changes, please review this and merge this.

**Comment by AnIkeT126** [comment]
@Chayan-11 and @vasu-1 this is an updated PR on https://github.com/vasu-1/CalcHub/pull/215 and issue https://github.com/vasu-1/CalcHub/issues/213 with the necessary changes, please review this and merge this.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Code is good to go...
But try to make is Responsive.

**Comment by AnIkeT126** [comment]
> Code is good to go... But try to make is Responsive.
@mansi-garg-12 upon request from @vasu-1 I have made the code responsive already, you can find the same piece of code under media queries in style.css


Please review it and merge it if it's fine.

**Comment by AnIkeT126** [comment]
@mansi-garg-12 upon request from @vasu-1 I have made the code responsive already, you can find the same piece of code under media queries in style.css

Please review it and merge it if it's fine, its been due for a week now.

**Comment by AnIkeT126** [comment]
@vasu-1 please merge this PR, upon reviewing it, as it has been over 4 days since I made the changes upon your initial request.

**Pull request closed without merging**
