### PR TITLE
Compound interest calculator

### LINKED ISSUE #209: compound interest calculator
### Calculator Functions

It will calculate the compound interest ,want to work on it.please assign me!

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by RiyaJain12**
This is the calculator which gives the value of compound interest.it will take the value of principal,time,rate and interest compounded.

## Description 📜

This is the calculator which gives the value of compound interest.it will take the value of principal,time,rate and interest compounded. fixes #209 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (147)

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — COMMENTED** [review]
Please chk @vasu-1 As this calculator is already exist....

**Comment by RiyaJain12** [comment]
@mansi-garg-12 this is previously opened by me but closing due to some issue and then create this issue again!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please Make It Responsive !!
And improve user interface !!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
still needs improvements in ui and responsiveness !!

**Comment by vasu-1** [comment]
any updates ?

**Comment by mansi-garg-12** [comment]
@vase please check this one too.....

**Comment by mansi-garg-12** [comment]
@vase please chek this one too.....

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
