### PR TITLE
My Calender

### PR DESCRIPTION
**Pull request by ug2510**
## Description

This application will help in tracking periods

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please make the different folder for CSS and JavaScript You have used same code two times.

**Comment by ug2510** [comment]
@mansi-garg-12 changes made!

**Review by mansi-garg-12 — APPROVED** [review]
Checked!! Ready to merge

**Comment by ug2510** [comment]
When will the pull request be merged? @mansi-garg-12

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image
 
Please change title !

Make a bit more responsive !

BTW niceee work !!

**Review by mansi-garg-12 — COMMENTED** [review]
Make these changes suggested by @vasu-1  then it will get merged.

**Comment by ug2510** [comment]
What should I do to make it more responsive?

**Comment by vasu-1** [comment]
> What should I do to make it more responsive?

use CSS media queries !!

**Comment by vasu-1** [comment]
closing the pull request due to inactivity !!

**Pull request closed without merging**
