### PR TITLE
Mortgage Calculator - Issue : #125

### PR DESCRIPTION
**Pull request by prathimacode-hub**
## Description 📜

This script aims to calculate mortgage interest. It is useful in measuring mortgage payments for banking websites (Indian Banks).
Fixes: #125 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

Mortgage Calculator

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
@prathimacode-hub since you've already added the SS of your calculator in your `Readme`, you don't have to separately make another folder to add your binary file. Please delete the `screenshot` folder as well as the binary file inside it.

**Comment by prathimacode-hub** [comment]
That's not a binary file. It's a .png file of a screenshot that's been called into README. So is it not needed? @Chayan-11

**Review by Chayan-11 — COMMENTED** [review]
Yeah it works fine now but please add the SS in the description while you're making the PR. 

image

**Comment by prathimacode-hub** [comment]
I added it up. @Chayan-11

**Review by Chayan-11 — APPROVED** [review]
Works fine !

**Comment by vasu-1** [comment]
image

image

Output is not showing!!!! @prathimacode-hub 

ps:) @Chayan-11 Please check the project once! Don't Rush!!

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Do necessary changes !

**Comment by prathimacode-hub** [comment]
I could see it from my link : https://prathimacode-hub.github.io/Mortgage-Calculator/index.html. Could you check it here with this link? I made some changes to the code and pushed it here too. @vasu-1 @Chayan-11

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image

Where is submit button ?

**Comment by vasu-1** [comment]
closing due to inactivity!!

**Pull request closed without merging**
