### PR TITLE
New PR for BMI Calculator

### LINKED ISSUE #22: BMI Calculator
### Calculator Functions

The objective of this JavaScript project is to wire up a very basic JavaScript BMI Calculator.
Key concepts covered :-
1.) document.querySelector()
2.) event listeners
3.) parseInt()
4.) toFixed()
5.) innerHTML

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by Kushal-2002**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #22 

<hr>
 
## Checklist ✅

- [ ✅] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [✅ ] I'm GSSOC'22 contributor
- [✅ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
BMIss

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
you were asked to delete your previous cloned repo as it had lots of conflicts and u had to freshly clone this and make a folder of BMI Calculator and add your code there but you didn't do that. Please check before making PR. Also you don't have to add your file to main `Readme`, it will be done from our end. Make the changes and add your code with your Readme file.

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
1. In your Readme folder, add features of your calculator, briefly describe what your BMI calculator can be used for (Remove this line saying `I've added the BMI calculator`, how does that adds any value?) and finally add the SS of your live server calculator.

2. Whatever video you're inserting in the readme folder remove that and add the same in `Description` while making a PR (and give access to that drive link, basically make the link public)

Take time and understand the workflow and then create PR, what's the rush ?

**Comment by Kushal-2002** [comment]
readme.md modified as per instructions.

**Comment by vasu-1** [comment]
@Chayan-11  review this

**Review by Chayan-11 — APPROVED** [review]
Looks good to me! @vasu-1

**Review by vasu-1 — APPROVED** [review]
LGTM @Kushal-2002

**Pull request merged**
