### PR TITLE
Visual Type Scale Calculator

### PR DESCRIPTION
**Pull request by sirilalithaadapa**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # <#42>

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot1
<hr>

### CODE REVIEW

**Review by Chayan-11 — APPROVED** [review]
@sirilalithaadapa great work, keep contributing ! 
@vasu-1 you can merge this PR, everything works fine

**Comment by sirilalithaadapa** [comment]
> @sirilalithaadapa great work, keep contributing ! @vasu-1 you can merge this PR, everything works fine

thanks.

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please Mention Functionalities and brief detail in the readme @sirilalithaadapa 

CC : @Chayan-11

**Comment by vasu-1** [comment]
And one more thing @sirilalithaadapa  
Have you copied the content from codepen ? If so than i can't merge it !
Please write css and js files in a good manner.
Copy paste in not allowed here !
Consider it as warning ! because it is against our code of conduct !

**Comment by sirilalithaadapa** [comment]
> Please Mention Functionalities and brief detail in the readme @sirilalithaadapa
> 
> CC : @Chayan-11

yeah sure will mention.

**Comment by sirilalithaadapa** [comment]
@vasu-1 , @Chayan-11 

i have updated the code,

check once, if any changes let me know will make changes.

thanks :)

**Review by Chayan-11 — COMMENTED** [review]
@sirilalithaadapa you've done all the work and kudos to you for that but I think what @vasu-1 asked you to do was to get a SS of live server and not the SS from `codepen.io` which also works fine but would be much better if you code it out in Visual Studio or any other editor and get a SS of the live server. I hope you get my point. @vasu-1 can correct me if I'm wrong.

**Comment by sirilalithaadapa** [comment]
> @sirilalithaadapa you've done all the work and kudos to you for that but I think what @vasu-1 asked you to do was to get a SS of live server and not the SS from `codepen.io` which also works fine but would be much better if you code it out in Visual Studio or any other editor and get a SS of the live server. I hope you get my point. @vasu-1 can correct me if I'm wrong.

yes, I have completed doing in it, 

You can check this ScreenShot

Used Editor: Visual Studio.

Screenshot (125)

**Comment by Chayan-11** [comment]
> > @sirilalithaadapa you've done all the work and kudos to you for that but I think what @vasu-1 asked you to do was to get a SS of live server and not the SS from `codepen.io` which also works fine but would be much better if you code it out in Visual Studio or any other editor and get a SS of the live server. I hope you get my point. @vasu-1 can correct me if I'm wrong.
> 
> yes, I have completed doing in it,
> 
> You can check this ScreenShot
> 
> Used Editor: Visual Studio.
> 
> Screenshot (125)

Yeah you've got it, but please update the same SS in your `Readme` file too, remove the earlier SS there and update that with this live server SS and if you can please remove those ads or may be crop them out.

**Comment by sirilalithaadapa** [comment]
> > > @sirilalithaadapa you've done all the work and kudos to you for that but I think what @vasu-1 asked you to do was to get a SS of live server and not the SS from `codepen.io` which also works fine but would be much better if you code it out in Visual Studio or any other editor and get a SS of the live server. I hope you get my point. @vasu-1 can correct me if I'm wrong.
> > 
> > 
> > yes, I have completed doing in it,
> > You can check this ScreenShot
> > Used Editor: Visual Studio.
> > Screenshot (125)
> 
> Yeah you've got it, but please update the same SS in your `Readme` file too, remove the earlier SS there and update that with this live server SS and if you can please remove those ads or may be crop them out.

Yea sure will crop it and later will update the readme.md file too.. thanks :)

**Comment by sirilalithaadapa** [comment]
completed updating the readme.md

**Review by Chayan-11 — APPROVED** [review]
Good work @sirilalithaadapa

**Review by vasu-1 — APPROVED** [review]
LGTM @sirilalithaadapa 
Nice Work !!

**Comment by sirilalithaadapa** [comment]
> LGTM @sirilalithaadapa Nice Work !!

Thanks :)

**Pull request merged**
