### PR TITLE
Added Permutation and Combination calculator

### PR DESCRIPTION
**Pull request by Pranav-Vyas**
## Description 📜
A simple calculator which will take the values of 'n' and 'r' and give no. of permutations and combinations of 'n' items taken 'r' at a time.
Fixes # <81>

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>
## Screenshots

img2

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — APPROVED** [review]
Good to go checked

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image

Make it responsive !!!

**Comment by Pranav-Vyas** [comment]
@vasu-1  Made it responsive. Please check.

**Review by vasu-1 — APPROVED** [review]
LGTM @Pranav-Vyas

**Pull request merged**
