### PR TITLE
Password Strength Calculator

### LINKED ISSUE #186: Password Strength Calculator
### Calculator Functions

Password Strength Calculator which calculates the strength in percentage of a user input password using HTML,CSS and Java Script.

### Contribution Event

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by Kushal-2002**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #186

<hr>
 
## Checklist ✅

- [✅ ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

password strength calc

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Code is good to go .
But you should remove the extra code which is not useful. That will enhance your code.

**Comment by Kushal-2002** [comment]
@mansi-garg-12 I have removed the extra code which was not useful.

**Comment by Kushal-2002** [comment]
@mansi-garg-12 @vasu-1 Can u please check the changes I have made?

**Comment by Kushal-2002** [comment]
@mansi-garg-12 @vasu-1 Please check the changes I have made

**Comment by vasu-1** [comment]
@mansi-garg-12 @Chayan-11 @AnuragParashar2000

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Make it responsive @Kushal-2002 
for devices like mobile and tablets

**Comment by vasu-1** [comment]
closing the pull request due to inactivity !!

**Pull request closed without merging**
