### PR TITLE
Lcm And Hcf Calculator

### PR DESCRIPTION
**Pull request by PothugantiChamili**
## Description 📜

I have built up Lcm and Hcf calculator through which we can perform both the operations on clicking on the respective buttons provided on it. 

##Built With :-
• Html, Css, Javascript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
lcm and hcf

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
Hey, I'm not sure of the stock photo which you used in the background, please change that or else give due credits.

**Comment by PothugantiChamili** [comment]
@Chayan-11 I have changed the background.

**Comment by PothugantiChamili** [comment]
@vasu-1 @Chayan-11 @mansi-garg-12   I have made the changes can you plz check.

**Review by Chayan-11 — APPROVED** [review]

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Checked

**Review by mansi-garg-12 — APPROVED** [review]

**Comment by PothugantiChamili** [comment]
@vasu-1  plz check the changes and merge this.

**Comment by PothugantiChamili** [comment]
@vasu-1 plz check the changes and merge this.

**Comment by PothugantiChamili** [comment]
@vasu-1 @Chayan-11  please merge this if the changes are ok.

**Comment by vasu-1** [comment]
A similar one may be found in our repository at https://vashishth.me/CalcHub/Calculators/Euclidean_Algorithm_Calculator/

closing this pr :)

**Comment by PothugantiChamili** [comment]
@vasu-1 @mansi-garg-12 should i make some changes in it because i have done two calculators past 15 days ago.

**Pull request closed without merging**
