### PR TITLE
Vehicle speed calculator

### PR DESCRIPTION
**Pull request by Arun9739**
## Description 📜

Issue : #295 

## About my calculator : 
I have made an calculator which takes input such as distance travelled by the vehicle and time taken to travel the distance. I also taken care of units.

My web page is full responsive for all devices, and the answer given by the calculator is accurate.

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Arun9739** [comment]
@mansi-garg-12 please reiew my pr.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove the binary file(.jpg).

**Comment by Arun9739** [comment]
@mansi-garg-12 done the changes ma'am

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
You can add some more features in it like if we put any two values then we will get third one value ......or may add some more features.

**Comment by vasu-1** [comment]
image

accept all the formats like in m, km, miles and also for time min, hour, second and perform necessary conversion.
Like [this](https://vashishth.me/CalcHub/Calculators/Unit%20Converter/)

**Pull request closed without merging**
