### PR TITLE
Kinetic Theory of Gases Calculator #286

### LINKED ISSUE #286: Kinetic Theory of Gases Calculator
### Calculator Functions

This calculator calculates 
Root Mean Square Velocity
Average Velocity 
Most Probable Velocity
Pressure of Gas
Volume of Gas
Temperature of Gas
Internal Energy

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by sharma-tanishq**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #286

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
Remove the `ScreenShot.jpeg` file

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please add some more features and changes in UI UX.

**Comment by sharma-tanishq** [comment]
> Please add some more features and changes in UI UX.

Now the Calculator also Shows the steps involved 
Background is also updated

**Review by Chayan-11 — COMMENTED** [review]
@mansi-garg-12

**Comment by sharma-tanishq** [comment]
> Update your recent screenshot of calculator in readme too.

Readme updated with new screenshot

**Review by mansi-garg-12 — APPROVED** [review]
Approved

**Review by vasu-1 — APPROVED** [review]
LGTM @sharma-tanishq 
Good Work!

**Comment by sharma-tanishq** [comment]
@vasu-1 Please add level tag as I am not getting points in the GSSOC 2022

**Pull request merged**
