### PR TITLE
multiplication table calculator , resolving issue 195

### PR DESCRIPTION
**Pull request by RiyaJain12**
calculate the multiplication table of any number depending upon the range given by the user.

## Description 📜

calculate the multiplication table of any number depending upon the range given by the user.It will also pointer the cursor when mouse keepon the get button and will also change the color of the button to specify that the pointer is on the button.
Fixes # 195

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (138)

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
Code works fine, but you can add some more features and functionalities and then brief about your calculator, that would add more value to the project.

**Comment by RiyaJain12** [comment]
@Chayan-11 Done!
Did some changes in the UI and the documentation.

**Review by Chayan-11 — APPROVED** [review]
Looks good to me !

**Review by vasu-1 — APPROVED** [review]
LGTM @RiyaJain12

**Pull request merged**
