### PR TITLE
New Calculator Added:Number System Conversion Calculator

### PR DESCRIPTION
**Pull request by sumithprabhu**
## Description 📜

This is the new Calculator Called the Number System Coversion Calculator , and is used  to convert Number of various systems into each other.
The sysytems can be :
- Decimal
- Binary
- Octal
- Hexadecimal

 #68 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Capture1234

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
@sumithprabhu 
* while you only uploaded your code which works fine, you also need to create a `README.md` folder inside `NumberSystemConversion_Calculator` sub-directory and there itself you can give a brief description about your calculator and its features and also upload your png file or ss and link to your video which you created. Please do add that and then create the PR. 

* Also, checkmark the checkbox while making PR. Just do this `- [X]` and you'll be good to go.

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
image

@sumithprabhu Look at the above image, there was no necessity of writing the same line twice in each paragraph - `The types of Number System which the calculator support are`. Please correct it.

**Comment by sumithprabhu** [comment]
Updated the readme file with suggested updates..

**Review by vasu-1 — APPROVED** [review]
LGTM @sumithprabhu

**Pull request merged**
