### PR TITLE
Decimal Number Calculator

### PR DESCRIPTION
**Pull request by ravenclaw-10**
## Description 📜

It calculates the decimal number , binary number, hexadecimal number and octal number from each other.

<hr>
 
## Checklist ✅

- [ x ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [ x ] I have performed a self-review of my own code or work.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] My changes generates no new warnings.
- [ x ] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot (34)

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove the binary file (like .png file ) .

**Comment by ravenclaw-10** [comment]
Okay sure.

**Comment by ravenclaw-10** [comment]
Done.

**Review by mansi-garg-12 — COMMENTED** [review]
Where is your README.md file

**Comment by ravenclaw-10** [comment]
Done

**Comment by vasu-1** [comment]
@mansi-garg-12 @Chayan-11 @AnuragParashar2000

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
@ravenclaw-10 you have to brief about your calculator and mention some of the functionalities and features in the readme file. Also you need to upload the SS of your calculator in the readme.

**Comment by ravenclaw-10** [comment]
Updated Readme.md. Please review it

**Review by mansi-garg-12 — APPROVED** [review]
Code is working file ...
good to go

**Comment by ravenclaw-10** [comment]
Please ignore the GCD calculator commit

**Review by Chayan-11 — APPROVED** [review]

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Found similar calculator in the project
https://vashishth.me/CalcHub/Calculators/NumberSystemCoversion_Calculator/

sorry for that @ravenclaw-10  ! I cannot merge this pr!

@mansi-garg-12 @Chayan-11  you should check the repository first before checking the pr!!

**Comment by vasu-1** [comment]
closing this pr!!
if you have any queries, reach out to me on discord :)

**Pull request closed without merging**
