### PR TITLE
added simple interest Calculator folder

### LINKED ISSUE #25: Simple Interest Calculator
I would like to add a Simple Interest Calculator with better UI.

### PR DESCRIPTION
**Pull request by codepley**
## Description 📜

Created Simple Interest Calculator which takes Principal, Rate and Time as input and calculates Interest and Amount.
Fixes #25 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## [x] Screenshots / Gif (Optional) 📸
calculator screenshot

<hr>

### CODE REVIEW

**Review by Chayan-11 — APPROVED** [review]
@vasu-1 you can merge this PR, works fine. The SS is uploaded in an image folder which won't be a problem.

**Comment by vasu-1** [comment]
> @vasu-1 you can merge this PR, works fine. The SS is uploaded in an image folder which won't be a problem.

listen in any folder binary file is not allowed @Chayan-11

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please Remove binary file(i.e image file)
and upload it directly in readme by simply copy and paste.
@codepley 

CC : @Chayan-11

**Comment by codepley** [comment]
Removed the image file and modified the readme.md with image link.
Please review this.

**Review by Chayan-11 — APPROVED** [review]

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
