### PR TITLE
Electric vs Petrol Economy Price Calculator

### LINKED ISSUE #282: Electric vs Gas Car Fuel Economy Calculator
### Calculator Functions

Fuel Price Comparison.
preview

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #282 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

preview

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove Binary files

**Comment by DragonUncaged** [comment]
> Please remove Binary files

Done!!

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
Add readme folder to brief about your calculator and upload SS of the calculator.

**Comment by DragonUncaged** [comment]
> Add readme folder to brief about your calculator and upload SS of the calculator.

i had added the SS but was asked to delete.

**Review by Chayan-11 — COMMENTED** [review]
She asked you to delete the stranded binary file. Now add a readme file and upload ss there itself and brief about your calculator and mention some of its features.

**Comment by DragonUncaged** [comment]
Done!!

**Review by Chayan-11 — APPROVED** [review]

**Review by mansi-garg-12 — APPROVED** [review]
checked good to go!!

**Comment by DragonUncaged** [comment]
If you find this good.
increase the level of the PR.

The animation and styling took time

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
