### PR TITLE
Added Daily Water Intake Calculator

### LINKED ISSUE #237: Daily Water Intake Calculator
### Description

This calculator helps you determine approximately the amount of water you must drink each day to avoid dehydration. However, this is only an estimate and the actual amount one needs depends on several factors like exercise, illness and fluid content in dietary intake.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by abhilipsasahoo03**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #237 
- Added Water Intake Calculator
- Made corresponding changes in README

<hr>
 
## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSOC'22 contributor
- [X] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

https://user-images.githubusercontent.com/80174214/163716353-21bc0048-4ad7-4405-9394-cc8bd6364835.mp4

Screenshot_2022-04-17-18-42-53-553_com android chrome
Screenshot_2022-04-17-18-43-02-526_com android chrome
Screenshot_2022-04-17-18-43-07-463_com android chrome

<hr>

### CODE REVIEW

**Comment by abhilipsasahoo03** [comment]
@mansi-garg-12 @Chayan-11 kindly look into the PR and let me know if any change is required

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Try to make it more responsive for smaller device and change your font size....

**Comment by abhilipsasahoo03** [comment]
Hi @mansi-garg-12 I have made it responsive for mobile, tab and desktop devices. Further, I have also changed font size and font styles to suitable ones. I have also made corresponding changes in README in order to add new screenshots and demo video. Please review and let me know if any further improvement is needed to be done.

**Review by mansi-garg-12 — APPROVED** [review]
good to go...
Ready to merged.

**Comment by abhilipsasahoo03** [comment]
Hi @mansi-garg-12 I have also resolved the merge conflicts. Kindly check and merge the PR if possible.

**Comment by abhilipsasahoo03** [comment]
Hi @mansi-garg-12 any updates on the status of my PR?

**Comment by abhilipsasahoo03** [comment]
Hey @mansi-garg-12 let me know the status of my PR.

**Review by vasu-1 — APPROVED** [review]
LGTM @abhilipsasahoo03 !!

**Pull request merged**
