### PR TITLE
Adding modulo and inverse modulo caclulator, Resolving issue #99

### LINKED ISSUE #99: Modulo and Inverse Modulo Calculator
## Description

This calculator will find out modulus and inverse modulus.

For ex:

7 mod 3=1
5^(-1) = 9 mod 11

@vasu-1 please assign this issue to me.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by AnIkeT126**
## Description 📜

This PR adds a calculator that aims to calculate the modulus and inverse modulus of two given numbers and is made using HTML, CSS & JS.

Fixes #99 
Updated PR on #120 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

image

image

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@vasu-1 pls check this PR now?

**Review by mansi-garg-12 — APPROVED** [review]
checked !!

**Comment by AnIkeT126** [comment]
@vasu-1 can you merge this PR, if it's ok??

**Review by vasu-1 — APPROVED** [review]
LGTM  @AnIkeT126

**Comment by AnIkeT126** [comment]
@vasu-1 this PR has been merge without any level and I have not been given points for this, kindly check this and award me the points for this PR.

**Pull request merged**
