### PR TITLE
Compound Interest Calci

### PR DESCRIPTION
**Pull request by PothugantiChamili**
## Description 📜

The basic idea of this calculator is to provide the amount and Compound Interest by providing principal amount, rate of interest, time taken using HTML , CSS , Javascript.

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (532)

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
you need to improve and enhance the user interface and also make it responsive. Add a Readme file to describe features of your calculator and add necessary ss.

**Comment by PothugantiChamili** [comment]
@Chayan-11 I have made the changes

**Comment by vasu-1** [comment]
> @Chayan-11 I have made the changes

it is not propagated here!!

**Comment by PothugantiChamili** [comment]
@vasu-1 I have made it now can u check it.

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
The changes aren't integrated here yet. Please recheck and add your files.

**Comment by Chayan-11** [comment]
> The changes aren't integrated here yet. Please recheck and add your files.

Also, Please read the instructions carefully as mentioned above

**Comment by PothugantiChamili** [comment]
@vasu-1 @Chayan-11  I have added all the files can u check it

**Comment by PothugantiChamili** [comment]
@vasu-1 @Chayan-11 is the code good to go.

**Review by mansi-garg-12 — COMMENTED** [review]
@vasu-1 please chk this one As this type of calculator already exist.

**Review by Chayan-11 — COMMENTED** [review]
C.I. calc is not present in repo. It was opened by one participant previously but there seems no updates @mansi-garg-12

**Comment by PothugantiChamili** [comment]
@Chayan-11 @vasu-1 I have made the changes it's ready to get merged.

**Comment by vasu-1** [comment]
Sorry for this inconvenience but we can't merge it as there was already another pr ([link](https://github.com/vasu-1/CalcHub/pull/210)) created before your pr's creation for compound interest. And it's got merged today.

suggestion :) you can edit the layout of the existing calculator and make it even more cool.

Happy Contributing !

**Pull request closed without merging**
