### PR TITLE
BaseX to BaseY Calculator

### LINKED ISSUE #77: Better UI & mobile responsiveness for BaseX calculator
### Calculator Functions

Will be great if I can improve the UI & mobile responsiveness for the BaseX calculator. Thank you 

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by hk2257853**
## Description 📜
Improved UI & Made Responsive using Bootstrap, Added a copy button to copy the result & Added an About section. Also included image in readme.md

Video link: https://drive.google.com/file/d/1X7T0FEpqdkou495jp9PI9U9MAeOAoy3v/view?usp=sharing

Fixes #77

<hr>
 
## Checklist ✅

- [ ✅] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I'm GSSOC'22 contributor
- [✅] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
From: 
Basexthen
TO:
basexcalc

<hr>

### CODE REVIEW

**Comment by hk2257853** [comment]
Please let me know if any changes are required!
last 2 questions:
1) What to do of the issue I created (this is my first open source contribution)?
2) Do I need to contact anybody to get the GSSOC2022 points if my changes are accepted?
Thank you.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove your .png file and add a screenshort in README.md

**Comment by hk2257853** [comment]
> Please remove your .png file and add a screenshort in README.md

Yeah that image is displayed in the README.md file. 
I saw in a youtube tutorial where he did like that. There's anytoher way to do show image in README.md without having the .png here?

**Comment by hk2257853** [comment]
Ma'am the changes are done. Please check n tell if any other change is required.
Thank you.

**Comment by Chayan-11** [comment]
> Please let me know if any changes are required! last 2 questions:
> 
> 1. What to do of the issue I created (this is my first open source contribution)?
> 2. Do I need to contact anybody to get the GSSOC2022 points if my changes are accepted?
>    Thank you.

If your PR gets merged raised against the issue, then your issue would be closed, nothing to worry about that and as far as your points are concerned it would be updated anyways as PA would mark the merged PRs accordingly to Level 1, 2 and 3 and you would get points following that and you don't have to worry about contacting anybody. Just keep Contributing !

**Comment by hk2257853** [comment]
> > Please let me know if any changes are required! last 2 questions:
> > 
> > 1. What to do of the issue I created (this is my first open source contribution)?
> > 2. Do I need to contact anybody to get the GSSOC2022 points if my changes are accepted?
> >    Thank you.
> 
> If your PR gets merged raised against the issue, then your issue would be closed, nothing to worry about that and as far as your points are concerned it would be updated anyways as PA would mark the merged PRs accordingly to Level 1, 2 and 3 and you would get points following that and you don't have to worry about contacting anybody. Just keep Contributing !

O thx for info🤗

**Review by mansi-garg-12 — APPROVED** [review]
Checked

**Review by Chayan-11 — APPROVED** [review]
Keep Contributing! @hk2257853

**Review by Chayan-11 — COMMENTED** [review]
We have decided to not move forward with UI changes. Keep contributing to other good issues.

**Comment by vasu-1** [comment]
Hey @hk2257853 
pulls with ui changes are not allowed !

Please create another unique calculator with great ui!!

Thanks !!

**Review by vasu-1 — APPROVED** [review]

**Comment by vasu-1** [comment]
LGMT @hk2257853 
Nice Work !!!!!

**Pull request merged**
