### PR TITLE
Tax Calculation, Fixed as per Indian tax Slab

### PR DESCRIPTION
**Pull request by sumithprabhu**
## Description 📜

As the topic itself describes the full scenario,the Tax Calculator was not set as per indian tax slab and the Health and Education cess was not added, the same issue has been resolved in this PR. #87 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Before Image of Tax Calculator for Rs 5 lakhs
tax1

After Image of Tax Calculator for Rs 5 lakhs
tax3
Indian Government Tax Calculator for Rs 5 lakhs (For Reference)
tax2

Calculator Video

https://user-images.githubusercontent.com/91826109/156988888-9405d334-afc1-4a8a-92ab-e019699a8559.mp4

<hr>

### CODE REVIEW

**Review by Chayan-11 — COMMENTED** [review]
@mansi-garg-12 Please check this

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
I think you have missed some files to push Please push all the files.

**Comment by sumithprabhu** [comment]
@mansi-garg-12 
Please can you elaborate.
As I have just changed the tax rates with the actual ones.

**Review by vasu-1 — APPROVED** [review]
Thanks for bug fix !! @sumithprabhu

**Pull request merged**
