### PR TITLE
Added function plotter files

### LINKED ISSUE #143: Function Plotter
### Calculator Functions

Add a function plotter built using vanilla JS, where users can enter their desired **valid** function and it will plot it on a canvas.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by XZANATOL**
## Description 📜

Added a function plotter, where users can enter their desired valid function and it will plot it on a canvas.
Fixes #143

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

function_plotter

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please check your code once your plot button is not working

**Comment by mansi-garg-12** [comment]
Check your button it is not working  ploy the graph of x-y=0

**Comment by XZANATOL** [comment]
the graph only prints functions of x variables contained in it. Like:
f(x) = sin(x)
f(x) = x^2 + 5
f(x) = x^2 + 5x + 2
The plotter plots the equation after the `=` sign.

**Comment by XZANATOL** [comment]
the Y input fields are used to print the scale size on the graph.

**Comment by mansi-garg-12** [comment]
OK let me check but it is also not working for sin(x).

**Comment by XZANATOL** [comment]
I did mention in the readme that it takes a function. functions usually are represented using x variables only. Also I adjusted the print ranges, you should see the functions represented normally now.

**Comment by mansi-garg-12** [comment]
@Chayan-11 @vasu-1   please chk this issue.

**Comment by XZANATOL** [comment]
@mansi-garg-12 @Chayan-11 @vasu-1 Any updates about the review?

**Comment by vasu-1** [comment]
@mansi-garg-12 @Chayan-11 @AnuragParashar2000

**Pull request closed without merging**
