### PR TITLE
added responsiveness for Matrix Adjoint and Inverse Calculator

### PR DESCRIPTION
**Pull request by patelyash5208**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # <issue_number_here>

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] Have you added a working video of your calculator ?
- [ ] I have specified the respective issue number.

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
can you just show some screenshots ? of different device sizes ?
ps: you can just copy and paste your images in this chat. it will automatically be uploded!

**Comment by patelyash5208** [comment]
Ya sure.

**Comment by patelyash5208** [comment]
image

image

image

**Review by vasu-1 — APPROVED** [review]
LGTM 🤩

**Pull request merged**
