### PR TITLE
Age Calculator Modified

### LINKED ISSUE #72: Modified UI for Age Calculator
### Calculator Functions

The current age calculator accepts birthday as the input, displays current date and outputs age. But the User Interface can be improved to a great extent. Please assign this issue to me so that I can make the necessary changes.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by shrutig-287**
## Description 📜

The user interface of the Age calculator has been modified, and the format of displaying current date and time changed as well.
Fixes #72 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Screenshot (521)

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please add some more features.

**Comment by vasu-1** [comment]
Similar one is already there
https://vashishth.me/CalcHub/Calculators/Age_Calculator/

Can't merge this pull :)
Closing this !

**Comment by vasu-1** [comment]
incase of any quires, feel free to reach out me on discord :)

**Comment by vasu-1** [comment]
sry for this 👍🏻

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
