### PR TITLE
added compound interest calculaor

### LINKED ISSUE #350: Compound Interest Calculator.
I have seen the all the calculators in the repository and get to know that compound interest calculator has already been made. I have also made the compound interest calculator with good UI. You can check mine's calculator [here](https://preet-sojitra.github.io/InterestCalculator/). 
Since this type of calculator is already been made, but I want to merge mine if you like the UI. 
So should I open pull request?

### PR DESCRIPTION
**Pull request by Preet-Sojitra**
## Description 📜

Added Compound Interest calculator with good looking UI.  I haven't added the calculator in `Readme.md` which exits in root of the repo, because already compound interest exists in it. If this PR gets merged, I will add this calculator there.
Fixes #350 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have specified the respective issue number.

<hr>

## Screenshots / Gif (Optional) 📸
image

image

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please Remove `Calculators/CompoundInterest_Calculator/src/images/calc.jpg` Binary file. 
Other than this, LGTM 🚀

**Comment by vasu-1** [comment]
while editing your `readme.md` just normally copy your image from device and paste it in github editor(while you edit in readme) . It will be uploaded automatically in github. you don't need to include in the files directory.

**Comment by Preet-Sojitra** [comment]
> while editing your `readme.md` just normally copy your image from device and paste it in github editor(while you edit in readme) . It will be uploaded automatically in github. you don't need to include in the files directory.

Made the necessary changes 👍

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Hey!
I recently realised that similar one is already there `https://github.com/vasu-1/CalcHub/tree/main/Calculators/Compound%20interest%20Calculator`.
So I suggest you to please edit the existing one , and make a better ui.
You can work on this pr itself.

**Comment by Preet-Sojitra** [comment]
> Hey! I recently realised that similar one is already there `https://github.com/vasu-1/CalcHub/tree/main/Calculators/Compound%20interest%20Calculator`. So I suggest you to please edit the existing one , and make a better ui. You can work on this pr itself.

What about deleting the existing one, and adding this one? I mean replacing existing one with this one

**Comment by Preet-Sojitra** [comment]
> > > Hey! I recently realised that similar one is already there `https://github.com/vasu-1/CalcHub/tree/main/Calculators/Compound%20interest%20Calculator`. So I suggest you to please edit the existing one , and make a better ui. You can work on this pr itself.
> > 
> > 
> > What about deleting the existing one, and adding this one? I mean replacing existing one with this one
> 
> Yes! As you are having better ui, you can edit existing one or replace that one.

Ok I will replace it soon

**Comment by Preet-Sojitra** [comment]
Deleted old compound interest calculator, and also added the path to new calculator in the `README.md` file which is in root of the repository

**Comment by Preet-Sojitra** [comment]
> Deleted old compound interest calculator, and also added the path to new calculator in the `README.md` file which is in root of the repository

@vasu-1 This PR is now ready to be merged.

**Review by vasu-1 — APPROVED** [review]
Great @Preet-Sojitra 
LGTM 🎉🎉

**Pull request merged**
