### PR TITLE
EMI Calculator

### PR DESCRIPTION
**Pull request by vaslal-324**
## Description 📜
EMI calculator for <b>home loan</b> was implemented using <b>html, css and js</b>.
 #155 

<h3>
<blockquote cite="https://www.bajajhousingfinance.in/how-to-calculate-home-loan-emi">
EMI = (P * r * (1 + r)^n)/ (((1 + r)^n) - 1) <br/>
where r is rate/(12*100)
</blockquote>
</h3>

<h4>Functionalities : </h4>
<ul>
    <li>Calculates EMI for home loan for values entered by the user.</li>
    <li>Can be used as a browser extension after minor modifications.</li>
</ul>

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

SS1

SS2

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
1. Brief about your calculator and add features and applications in the Readme folder
2. Make a block quote for the Formula to calculate EMI
3. Upload SS both in Description as well as in the Readme folder
4. Please mention what EMI calculator it is : Home, Car, Personal and accordingly I can check whether it is matching with according to Indian Standards because currently I see only random value generating which seems confusing.

**Comment by vaslal-324** [comment]
Okay, I'll incorporate the changes

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
* The SS hasn't been uploaded in the Readme folder. Simply select the SS from your local system by clicking your cursor at `Attach files by dragging & dropping, selecting or pasting them.
`  at the bottom of your Readme.

* Also, please fix the same in description too.

* You also need to remove binary files (i.e.) `SS1.png` and `SS2.png` from your `EMI_Calculator` folder. Just delete them and instead upload those SS into your Readme folder by following the above process.

**Comment by vaslal-324** [comment]
Thank you for letting me know, I have fixed the changes.

**Review by Chayan-11 — APPROVED** [review]
Looks good to me! @vasu-1

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
