### PR TITLE
Gpa calculator

### LINKED ISSUE #113: GPA calculator
### Calculator Functions

Performs the calculation of the GPA based on Grades and Credit hours entered by the user.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by miraehab**
## Description 📜

I added the GPA Calculator that takes from the user the courses (name, credit hours, grade) and based on the input calculate the GPA .

Fixes #113 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
Calculator overview
<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove Calculators/GPA_Calculator/images/images.jpg this file and add in link where you have used this background image

**Comment by miraehab** [comment]
I made the required changes, you can check it now @mansi-garg-12

**Review by vasu-1 — CHANGES_REQUESTED** [review]
LGTM @miraehab 
But it is not responsive !!

image

please,  make it responsive!!

**Comment by miraehab** [comment]
I made the calculator responsive, you can check it now @vasu-1

**Pull request merged**
