### PR TITLE
Added new Arithmetic Calculator (with more functionalities)

### PR DESCRIPTION
**Pull request by TusharKesarwani**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # 1 Added New Arithmetic Calculator
Fixes # 2 Added functionalities like - Percentage Calculation, Memory Add, Memory Subtract, Memory Recall & Memory Clear

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
Calculator

<hr>

### CODE REVIEW

**Comment by vasu-1** [comment]
You can edit the existing calculator !
Don't need to create another calculator !

**Comment by vasu-1** [comment]
just revert back all the commits and edit the existing one !

**Comment by TusharKesarwani** [comment]
Ok sir

**Comment by TusharKesarwani** [comment]
Sir, I have created new PR.
Please review that PR and close this PR.
Link of the new PR:-
https://github.com/vasu-1/CalcHub/pull/324

**Pull request closed without merging**
