### PR TITLE
Transpose of 3x3 Matrix Calculator

### LINKED ISSUE #111: Transpose of 3X3 Matrix Calculator
### Calculator Functions

This Calculator will calculate the transpose of 3X3 Matrix.

I am GSSOC 22 contributor. Please assign me this issue.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by ShruthiKartik**
## Description 📜
Transpose of 3X3 Matrix Calculator #111

Transpose of a matrix is found by interchanging the rows and columns of a matrix. This calculator calculates the transpose of 3X3 matrix. I have added the code of Transpose of 3X3 Matrix Calculator. It is built with- HTML,CSS and JavaScript.
I have added the README.md of Transpose of 3X3 Matrix Calculator.

Fixes #111

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
image
image
<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
@ShruthiKartik everything works fine in this PR but if you can add some 3-4 features/functionalities of your calculator, it would be good contrary to a one-liner definition in your Readme file.

**Comment by ShruthiKartik** [comment]
@Chayan-11 Should I add more description about the features of Calculator in Readme file?

**Comment by Chayan-11** [comment]
> @Chayan-11 Should I add more description about the features of Calculator in Readme file?

yes, that's what I asked for

**Comment by ShruthiKartik** [comment]
@Chayan-11 Okay, Will do the necessary changes!

**Comment by ShruthiKartik** [comment]
@Chayan-11 I have updated the Readme file.

**Review by Chayan-11 — APPROVED** [review]
Good work!

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
