### PR TITLE
Final velocity calculator 

### LINKED ISSUE #221: Final Velocity Calculator
### Calculator Functions

# Calculator Use 💯
This velocity calculator uses the equation that the final velocity of an object is equal to its initial velocity added to its acceleration multiplied by time of travel. This calculator does assume constant acceleration during the time traveled.

Velocity Equation in these calculations:
Final velocity (v) of an object equals initial velocity (u) of that object plus acceleration (a) of the object times the elapsed time (t) from u to v.

# v=u+at
Where:
u = initial velocity
v = final velocity
a = acceleration
t = time

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by maheshdbabar9340**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #221

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

try

<hr>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
Remove those 2 binary files and briefly elaborate about your calculator instead of one liner, add features and functionalities and in readme itself upload your SS of calculator.

**Comment by maheshdbabar9340** [comment]
> Remove those 2 binary files and briefly elaborate about your calculator instead of one liner, add features and functionalities and in readme itself upload your SS of calculator.

Completed all changes. Please let me know if any more changes are required.
 
Thank You. 

Waiting for your good response,

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Make it responsive !
Improve user interface !

**Comment by maheshdbabar9340** [comment]
> Make it responsive ! Improve user interface !

@vasu-1 I completed given changes and now user interface is responsive as well as user friendly. 

Also I changed readme.md file where everyone will get idea about final_velocity_calculator by reading it.

Please let me know if any more changes are required.

Thank You.

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image

change font color !!!
it is not visible !!

**Comment by maheshdbabar9340** [comment]
> image
> 
> change font color !!! it is not visible !!

@vasu-1  I completed given changes and made it visible.

Please let me know if any more changes are required.

Thank You.

**Comment by vasu-1** [comment]
Can you please make a calculator for the other two equations?

d = ut + (1/2)at^2
v^2 - u^2 = 2ad

**Comment by vasu-1** [comment]
@maheshdbabar9340

**Comment by vasu-1** [comment]
closing due to inactivity !

**Pull request closed without merging**
