### PR TITLE
GST Calculator

### LINKED ISSUE #269: Add GST Calculator
### Calculator Functions

A simple website that takes Gross Price & GST Rate as the input and returns Net Price & SGST/CGST as output.
Shows output only for valid GST Tax slabs.
Throws an error for invalid ones.

VAT calculator is already a part of the repo but since VAT is no longer a valid tax regime,it would be great to replace it with a GST Calculator.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by BabyElias**
## Description 📜

Added a GST Calculator
Fixes #269 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
imagee

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove binary files(.jpg and .png)

**Comment by BabyElias** [comment]
@mansi-garg-12 Removed the files

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
image
Please check your code for phone and tablet from right hand side.
And enhance the UI / UX of your project.

**Comment by BabyElias** [comment]
@mansi-garg-12 In order to improve the UI I would need to add binary files to my contribution. Should I?

**Comment by BabyElias** [comment]
New Layout & Responsiveness Check
image

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
image
check your code your button is not working showing some errors.

**Comment by BabyElias** [comment]
@mansi-garg-12  The output will be visible only for valid GST Tax slabs i.e 5,12,18 & 28%
image

**Comment by BabyElias** [comment]
@mansi-garg-12 Please review if any changes are needed

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
please integrate your all CSS files.

**Comment by mansi-garg-12** [comment]
just put all all your CSS code in single files and you may chk youtube video .

**Review by vasu-1 — CHANGES_REQUESTED** [review]
You have to include only three files :)
`index.html, script.js, style.css`

Please remove all the min.css files as you can use the cdn !

**Pull request closed without merging**
