### PR TITLE
DayCalculator

### LINKED ISSUE #148: DayCalculator
### Calculator Functions

This calculator helps you to find the day of any date.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by parikhvedant2003**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #148 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by AnuragParashar2000** [comment]
@parikhvedant2003  please add some screenshots of your working code in Readme.md and remove the uploaded png files, the text in the calculator is black which is not visible in the black background, also there is no column to show the calculated day.
image

**Comment by parikhvedant2003** [comment]
@AnuragParashar2000  I have checked all my stuff but it is working properly
Screenshot (161)

**Comment by vasu-1** [comment]
@parikhvedant2003 Mention your issue number here !

image

**Comment by vasu-1** [comment]
@AnuragParashar2000 @mansi-garg-12 @Chayan-11

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove .png files and add a screenshot in README.md

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
you were asked to remove the binary file, delete `DayCalculator.png` from your folder and also add some features of your calculator in Readme.

**Comment by parikhvedant2003** [comment]
Hey guys!!! @Chayan-11 and @mansi-garg-12 , pls check it once and tell me now what should I improve?

**Review by Chayan-11 — APPROVED** [review]
Good work @parikhvedant2003, looks good to me.

**Review by Chayan-11 — COMMENTED** [review]
@mansi-garg-12 do you want any other changes?

**Review by mansi-garg-12 — APPROVED** [review]
great work , good to go

**Comment by parikhvedant2003** [comment]
Thanks to @vasu-1 , @Chayan-11 and @mansi-garg-12 🙏🙏🙏

**Review by vasu-1 — APPROVED** [review]
LGTM @parikhvedant2003

**Pull request merged**
