### PR TITLE
Modified Currency Calculator with many currencies- Issue no:198

### PR DESCRIPTION
**Pull request by Abhishek786-Kolvekar**
#198 
Please look into this.
@vasu-1 and other mentors
Regards

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Code is good to go...
But try to make it responsive for phone and tablet.

**Comment by Abhishek786-Kolvekar** [comment]
Thanks for feedback @mansi-garg-12

**Review by mansi-garg-12 — APPROVED** [review]
OK thanks for confirmation.....
Code is good to go..
Nice work

**Review by vasu-1 — CHANGES_REQUESTED** [review]
please restore readme.md
it is removed by you!!!!!!

@mansi-garg-12 check this again ! he has removed the readme!!

**Comment by Abhishek786-Kolvekar** [comment]
Oops. Please give me a minute. I will send.

**Comment by Abhishek786-Kolvekar** [comment]
https://user-images.githubusercontent.com/81409657/163847644-a1710cf3-97ba-4fc1-a2d5-4c2f7cfcfa54.mp4
image

**Comment by Abhishek786-Kolvekar** [comment]
Should I create a new branch?

**Comment by Abhishek786-Kolvekar** [comment]
#259 
Please check this @vasu-1 .
Sorry once again @mansi-garg-12 @vasu-1

**Pull request closed without merging**
