### PR TITLE
Divisors Calculator

### LINKED ISSUE #281: Divisors Calculator
### Calculator Functions

Calculator that takes a number and gives its divisors with time complexity O(sqrt(n))

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by miretteamin**
## Description 📜

Divisors calculator calculates all-natural factors for a number.
Fixes #281 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
image

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
please remove those binary files.

**Comment by miretteamin** [comment]
> please remove those binary files.

I'm sorry I'm kinda confused about which ones? what are their names

**Review by mansi-garg-12 — COMMENTED** [review]
Calculators/Divisors Calculator/background.jpg
remove this

**Comment by miretteamin** [comment]
> Calculators/Divisors Calculator/background.jpg remove this

Done.

**Review by vasu-1 — APPROVED** [review]
Cool @miretteamin 
LGTM !

**Comment by miretteamin** [comment]
> Cool @miretteamin 
> LGTM !

Thank you a lot!! :)
Sorry for the disturbance but the score hasn't been added on the leaderboard 😅

**Comment by miretteamin** [comment]
> > Cool @miretteamin 
> > LGTM !
> 
> @vasu-1 
Thank you a lot!! :)
> Sorry for the disturbance but the score hasn't been added on the leaderboard 😅

**Comment by vasu-1** [comment]
> > > Cool @miretteamin 
> > > LGTM !
> > 
> > @vasu-1 
> Thank you a lot!! :)
> > Sorry for the disturbance but the score hasn't been added on the leaderboard 😅
> 
> 

It would be updated after sometimes !!

**Comment by miretteamin** [comment]
> > > > Cool @miretteamin 
> > > > LGTM !
> > > 
> > > @vasu-1 
> > Thank you a lot!! :)
> > > Sorry for the disturbance but the score hasn't been added on the leaderboard 😅
> > 
> > 
> 
> It would be updated after sometimes !!

Okay thank you a lot! 🙂

**Pull request merged**
