### PR TITLE
Trigonometric Calculator🧮

### LINKED ISSUE #248: Trigonometric Calculator
### Calculator Functions

**Description**
I want to add a **Trigonometric calculator** which will help to calculate the **sin, cos,tan** value of any given angle and it will display the relevant result .

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by Mrjoy832**
## Description 📜
Trigonometric calculator is a calculator which will help to calculate the sin, cos,tan value of any given angle and it will display the relevant result . It's made using HTML,CSS,JS

---

Fixes #248 

<hr>
 
## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSOC'22 contributor
- [X] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
image

https://user-images.githubusercontent.com/77873383/163701322-04ac5ac1-886b-4c0b-9d3b-b779de61ba07.mp4

<hr>

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@mansi-garg-12 , @Chayan-11  please check it

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Code is good to go But try to make it responsive....

**Comment by Mrjoy832** [comment]
> Code is good to go But try to make it responsive....

https://user-images.githubusercontent.com/77873383/163727136-3f804903-62b9-4eed-bfaa-906e16d42ed7.mp4


Hey @mansi-garg-12 , It's already responsive..kindly look into the video

**Comment by vasu-1** [comment]
similar functionalities can be found in https://vashishth.me/CalcHub/Calculators/Scientific_Calculator/

closing this pr :)

**Comment by Mrjoy832** [comment]
> similar functionalities can be found in https://vashishth.me/CalcHub/Calculators/Scientific_Calculator/
> 
> closing this pr :)

It's Scientific Calculator but mine is specifily for Trigonometric values....I put lot of effort on it...mentor mansi also told about merging ...now why are you closing it?

**Pull request closed without merging**
