### PR TITLE
Add Matrix Adjoint And Inverse Calculator

### LINKED ISSUE #2: [Create New Issue]: Matrix Adjoint and Inverse Calculator
### Calculator Functions

Take User Input Matrix and display the Adjoint and Inverse of that matrix.

I would like to work on this issue can you assign this to me.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by kaustav202**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #2 

Completed Task of Matrix Calculator as assigned.
<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I'm GSSOC'22 contributor

## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please check your code once your calculate button is not working .

**Comment by kaustav202** [comment]
Okay I'm looking into it.

**Comment by kaustav202** [comment]
> Please check your code once your calculate button is not working .

Resolved All issues .This should work fine now

**Comment by kaustav202** [comment]
Please review the changes @mansi-garg-12  @vasu-1  @Chayan-11

**Review by mansi-garg-12 — COMMENTED** [review]
Checked

**Comment by kaustav202** [comment]
> Checked

Thank you

**Review by vasu-1 — APPROVED** [review]
LGTM @kaustav202

**Pull request merged**
