### PR TITLE
Modified Currency Calculator with many currencies

### PR DESCRIPTION
**Pull request by Abhishek786-Kolvekar**
I had checked that the currency calculator in your repo had less number of currencies to convert.
So I used another API that has an extensible range of currencies.
Please revert for any changes.

### CODE REVIEW

**Comment by Abhishek786-Kolvekar** [comment]
#188

**Comment by Abhishek786-Kolvekar** [comment]
@Chayan-11 Please review mine too.

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
image
 
@Abhishek786-Kolvekar I would suggest please change the font color of `Converted Amount` text and also change the color of the heading `Currency Converter` and that's good that you commented your code while making the necessary changes.

**Comment by Abhishek786-Kolvekar** [comment]
I will do it right away.

**Comment by Abhishek786-Kolvekar** [comment]
image

**Comment by Abhishek786-Kolvekar** [comment]
Any further changes?

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
you haven't commit the changes and pushed into main branch, it's not showing here. Please recheck again and then push your changes.

**Comment by Chayan-11** [comment]
> I will do it right away. The image sent by you is mine? Because I have given background color.

yes obvious its yours.

**Comment by Abhishek786-Kolvekar** [comment]
I have created a new branch for the same.
Issue: #188 
PR: #198

**Comment by vasu-1** [comment]
@mansi-garg-12 @Chayan-11 @AnuragParashar2000

**Pull request closed without merging**
