### PR TITLE
Modified Currency Calculator with README file

### PR DESCRIPTION
**Pull request by Abhishek786-Kolvekar**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # <issue_number_here>

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x ] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GSSOC'22 contributor
- [ x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Comment by Abhishek786-Kolvekar** [comment]
https://user-images.githubusercontent.com/81409657/163851644-6bef3cb7-285a-48ee-864c-3054dcc9e979.mp4

image

**Comment by Abhishek786-Kolvekar** [comment]
@vasu-1 @mansi-garg-12

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please delete extra files..

**Comment by Abhishek786-Kolvekar** [comment]
Hello Mansi,
There are no extra files. All are part of the project.

**Review by mansi-garg-12 — APPROVED** [review]
Code is good to go...

**Comment by Abhishek786-Kolvekar** [comment]
@mansi-garg-12 @vasu-1 Any status about my pull request?

**Review by vasu-1 — APPROVED** [review]
LGTM @Abhishek786-Kolvekar

**Pull request merged**
