### PR TITLE
✔️Graph Calculator (check Deployment✔️) (changes done )

### LINKED ISSUE #293: Graph Calculator
### Calculator Functions

Write any arithmetic or trigonometric equation and get the graph for that

image

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #293 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>
image

### CODE REVIEW

**Comment by DragonUncaged** [comment]
Check This Also it works fine on my computer.
https://github.com/vasu-1/CalcHub/pull/288

**Review by Chayan-11 — COMMENTED** [review]
Does this graph works for only 3 functions?

**Review by Chayan-11 — COMMENTED** [review]
Please clearly describe the features of your calculator and for which functions is it valid to by adding a readme file and attaching ss.

**Comment by DragonUncaged** [comment]
> Please clearly describe the features of your calculator and for which functions is it valid to by adding a readme file and attaching ss.

Done !

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
image
Please make some improvement in UI and UX.
Nice work!!

**Comment by DragonUncaged** [comment]
> image Please make some improvement in UI and UX. Nice work!!

This is the problem from your side i think in my computer it looks good..

**Comment by DragonUncaged** [comment]
Check This Deployment
https://replit.com/@DragonUncaged/graph

**Comment by DragonUncaged** [comment]
https://graph.dragonuncaged.repl.co

**Comment by DragonUncaged** [comment]
Also Check This One
https://github.com/vasu-1/CalcHub/pull/288

**Review by mansi-garg-12 — APPROVED** [review]
ready to merge !! nice work

**Review by vasu-1 — APPROVED** [review]
Awesome @DragonUncaged 
LGTM  🚀

**Review by vasu-1 — APPROVED** [review]
Awesome @DragonUncaged 
LGTM  🚀

**Pull request merged**
