### PR TITLE
👍 Covid Calculator 

### LINKED ISSUE #283: Covid Case Calculator
### Calculator Functions

From the given Population and
Case Mortality Rate and infection rate

preview

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #283

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

preview

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove binary files

**Comment by DragonUncaged** [comment]
@mansi-garg-12 Done!!

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
same goes here too, add readme folder and brief about your calculator.

**Comment by DragonUncaged** [comment]
> same goes here too, add readme folder and brief about your calculator.

done!!

**Review by Chayan-11 — APPROVED** [review]

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
image
Please improve it UI / UX in case of phone and tablet.

**Comment by DragonUncaged** [comment]
Done !!

image

**Comment by DragonUncaged** [comment]
If you find this good.
increase the level of the PR

**Review by vasu-1 — CHANGES_REQUESTED** [review]
image


Fix the alignment and colors of texts!

**Comment by DragonUncaged** [comment]
as you can see in my browser it works fine

**Comment by DragonUncaged** [comment]
https://covid.dragonuncaged.repl.co/

**Review by vasu-1 — APPROVED** [review]

**Pull request merged**
