### PR TITLE
Adding 3D Shapes Volume Calculator

### LINKED ISSUE #254: Add Volume of 3D Shapes Calculator
### Calculator Functions

This will calculate the volume of 3D shape that is Cube.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by Rakesh9100**
## Description 📜

I have added a calculator to calculate the volume of different 3D shapes.
Fixes #254 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
This PR contain two PR chk it out...

**Comment by Rakesh9100** [comment]
> This PR contain two PR chk it out...

Please check again it's showing one only now.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please try to make it responsive for phone and tablet.

**Comment by mansi-garg-12** [comment]
Nope it will merge when you will make it responsive...
Try to make it responsive.

**Comment by Rakesh9100** [comment]
> Nope it will merge when you will make it responsive... Try to make it responsive.

Kindly check its done.

**Review by vasu-1 — CHANGES_REQUESTED** [review]
Please make it responsive ! @Rakesh9100 
suggestion: `use bootstrap`

**Comment by Rakesh9100** [comment]
Done @mansi-garg-12 Check it out

**Pull request closed without merging**
