### PR TITLE
Added Medical insurance File

### LINKED ISSUE #279: Medical insurance Calculator
### Calculator Functions

Calculate for the Family and Organization as well

image

image

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #279 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

preview

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove Binary file like (.png file).

**Comment by DragonUncaged** [comment]
Removed .gif and ,jpg file

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove all binary files(.svg)

**Comment by DragonUncaged** [comment]
Done !!

**Comment by vasu-1** [comment]
plagiarized content found !!

**Comment by DragonUncaged** [comment]
> 

Ya !! It is inspired from that website...

**Comment by DragonUncaged** [comment]
> plagiarized content found !!
> 
> `https://berniesanders.com/issues/how-does-bernie-pay-his-major-plans/` `https://lifehacker.com/how-bernie-sanders-plans-to-pay-for-everything-1841931880/`

visit this website and see nothing is copied just the frontend is inspired from that.

**Pull request closed without merging**
