### PR TITLE
Weight calculator created

### LINKED ISSUE #337: Weight Calculator
### Calculator Functions

Weight will be calculated in grams ,kilograms , pounds and ounces simultaneously.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by piyusha2001**
## Description 📜

Created weight calculator that takes input and displays weight simultaneously in kilograms, grams, ounces and pounds 

Fixes #337 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

Screenshot 2022-05-26 131204

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove binary files like (.jpg files)

**Comment by vasu-1** [comment]
remove binary files @piyusha2001 !

**Comment by vasu-1** [comment]
Similar one cab be found [here](https://vashishth.me/CalcHub/Calculators/Unit%20Converter/)

Can't merge this pull!

**Comment by vasu-1** [comment]
incase of any queries feel free to reach out me on discord :)

**Pull request closed without merging**
