### PR TITLE
Sleep Calculator added

### LINKED ISSUE #165: Sleep Calculator
### Calculator Functions

Sleep Calculator which calculates the amount of sleep which is needed by an individual based on their age. 
Using HTML,CSS and JS.

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by Kushal-2002**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #165

<hr>
 
## Checklist ✅

- [✅ ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

Screenshot (6)

### CODE REVIEW

**Comment by vasu-1** [comment]
@Chayan-11 @mansi-garg-12

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
1. you can add some more features asking the users about which time they would like to wake up and accordingly it would show the adequate timings along with no. of sleep cycles instead of simply putting in D.O.B and getting the recommended duration of sleep according to age. It would turn obvious that a 20 year old would be recommended to sleep for 7-9 hours according to standards. Basically turn it more intuitive by adding those features.

2. Add features and applications about your calculator in Readme and recheck your SS uploaded in description.

3. Check your Readme again `Inputs required for calculation of BMI`, while you copy/paste from your previous project, keep these checked before making the PR.

**Comment by Kushal-2002** [comment]
@Chayan-11 I have added the new features and modified the readme.md file.

**Review by Chayan-11 — APPROVED** [review]
This one works much better than the former. good work @Kushal-2002

**Review by vasu-1 — APPROVED** [review]
LGTM @Kushal-2002

**Pull request merged**
