### PR TITLE
Added Cubic_Equation_Calc files

### LINKED ISSUE #142: Cubic Equation Calculator
### Calculator Functions

Add a calculator that solves equations of third degree. (a*X^3 + b*X^2 + c*X + d = 0)

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by XZANATOL**
## Description 📜

Added a calculator that solves equations of third degree. (aX^3 + bX^2 + c*X + d = 0) and print out its roots
Fixes #142 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

Calculator is responsive on Desktop & Mobile devices.

image

image

<hr>

### CODE REVIEW

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please check your code once its not giving the right solution.

**Comment by XZANATOL** [comment]
@mansi-garg-12 can you provide me with the failing test case you tried?

**Comment by mansi-garg-12** [comment]
image

**Comment by XZANATOL** [comment]
@mansi-garg-12 should be good now.

**Review by mansi-garg-12 — APPROVED** [review]
checked!!
Ready to merge

**Review by vasu-1 — APPROVED** [review]
LGTM @XZANATOL

**Pull request merged**
