### PR TITLE
Pot Calculator

### PR DESCRIPTION
**Pull request by PothugantiChamili**
## Description 📜

This is basically a Pot Calculator which will help to calculate whether the number of pots can be made within the given time or not within the quantity of mud available to us..

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸
pot calculator

<hr>

### CODE REVIEW

**Comment by PothugantiChamili** [comment]
@mansi-garg-12 please check and merge this.

**Comment by PothugantiChamili** [comment]
@vasu-1 is it ready to merge.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
its a very simple calculator Please try to make something good...

**Comment by PothugantiChamili** [comment]
@mansi-garg-12 I have made the unique calculator is there some changes to be made plz specify.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Your PR does not contain a README.md file and Having only HTML file please form different different file for javascript , CSS , HTML.

**Pull request closed without merging**
