### PR TITLE
Scientific Calculator with UI #51

### PR DESCRIPTION
**Pull request by Gaurika-Gupta**
> ## Description 📜
> Solved Issue #51 
> 
> ## Checklist ✅
> * [x]  I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
> * [x]  I have performed a self-review of my own code or work.
> * [x]  I have commented on my code, particularly in hard-to-understand areas.
> * [x]  My changes generates no new warnings.
> * [x]  I'm GSSOC'22 contributor
> 
> ## Screenshots / Gif (Optional) 📸
>

### CODE REVIEW

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
@Gaurika-Gupta Can you please make a Readme.md folder and upload your image there itself instead of uploading binary file. @vasu-1 everything else works fine.

**Review by Chayan-11 — CHANGES_REQUESTED** [review]
And also please briefly describe about your calculator and check mark the checkbox before creating the PR @Gaurika-Gupta

**Comment by Gaurika-Gupta** [comment]
I have made the above changes. 
Which checkbox should I checkmark? 
Please merge if you think everything is good enough.

**Review by Chayan-11 — COMMENTED** [review]
@vasu-1 please look into this, works fine for me.

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please upload your png file in README.md or paste a link of drive.

**Comment by vasu-1** [comment]
ui changes will not be counted in Gssoc Contribution !!
if you still want to work on this than you can, otherwise you can make another unique calculator !!

**Comment by vasu-1** [comment]
Closing this pull due to inactivity !!

**Pull request closed without merging**
