### PR TITLE
Adding Affine Cipher Calculator, resolving issue #64

### LINKED ISSUE #64: Affine Cipher Calculator
### Calculator Functions

The affine cipher is a type of monoalphabetic substitution cipher where each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter.

Text :  MONEY
a=11
b=4
Cipher: XGCRWI

Can I work on this issue as a part of GSSoC'22 @vasu-1 ?

### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.

### PR DESCRIPTION
**Pull request by AnIkeT126**
## Description 📜

This calculator is designed for the encryption and decryption of affine cipher using HTML, CSS , JS.

Fixes #64 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

af1

af2

af3

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@vasu-1 can you review this PR?

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Please remove .png file and add a screenshot in README.md file.

**Comment by AnIkeT126** [comment]
ok @mansi-garg-12

**Comment by AnIkeT126** [comment]
@mansi-garg-12 I have created a new PR, with the suggested changes.
I am closing this one for now

**Pull request closed without merging**
