### PR TITLE
Arithmetic Equation

### LINKED ISSUE #339: Arithmatic Equation Solver
### Contribution Event

GSSOC22

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #339

<hr>
 
## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

image

### CODE REVIEW

**Comment by DragonUncaged** [comment]
Also Check This

https://github.com/vasu-1/CalcHub/pull/288

**Review by mansi-garg-12 — CHANGES_REQUESTED** [review]
Nice calculator.
But Make some improvement in UI/UX.

**Comment by DragonUncaged** [comment]
> Nice calculator. But Make some improvement in UI/UX.

I have made it responsive as well. And UI is in its best as far as i can do..

**Review by vasu-1 — APPROVED** [review]
LGTM @DragonUncaged

**Pull request merged**
