### PR TITLE
Speed Unit Converting Calculator

### PR DESCRIPTION
**Pull request by ravenclaw-10**
## Speed converting calculator takes speed of any unit with user and gives the speed value in other required speed unit.

e.g it converts 
(i) MPS to KMPH and MPH.
(ii) KMPH to MPS and MPH.
(iii) MPH to MPS and KMPH.

<hr>
 
## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>
scc1
<hr><hr>
scc2

<hr>

### CODE REVIEW

**Comment by ravenclaw-10** [comment]
It is working, it changes the inner html which shows result (below the calculate button).
Please recheck it.

**Comment by mansi-garg-12** [comment]
Provide the screenshot as it is not working.

**Comment by vasu-1** [comment]
image


Fix this pull description :)

**Comment by vasu-1** [comment]
Sorry to inform you that these functionalities are already there in [this calculator](https://vashishth.me/CalcHub/Calculators/Unit%20Converter/) . 
We can't merge this pull !

You can work on other calculator or on enhancements if needed !

**Pull request closed without merging**
