### PR TITLE
Modified Currency Calculator with many currencies-UI changes

### PR DESCRIPTION
**Pull request by Abhishek786-Kolvekar**
#188 

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

### CODE REVIEW

**Review by vasu-1 — CHANGES_REQUESTED** [review]
LGTM @Abhishek786-Kolvekar 

But, there is already one currency calculator ! you can change that existing code according to your issue statement !

**Comment by Abhishek786-Kolvekar** [comment]
Hello Vasu,
I tried to change that code, but I ended up messing up the UI.
So, I thought I would create a new one.
I will try once again.
Regards

**Review by vasu-1 — CHANGES_REQUESTED** [review]
You can change [this](https://github.com/vasu-1/CalcHub/tree/main/Calculators/Currency_Calculator) Folder.
Don't make another folder for the same

**Comment by Abhishek786-Kolvekar** [comment]
#229 
Please refer this @vasu-1 @Chayan-11

**Pull request closed without merging**
